### ISSUE TITLE
Table 'structure_surfer.gene_info' doesn't exist

### ISSUE THREAD

**Issue by lcscs12345** [nberkow/StructureSurfer#3]
```
mysql -u root -p < structure_surfer.mysql 
Enter password: 
ERROR 1146 (42S02) at line 26: Table 'structure_surfer.gene_info' doesn't exist
```

**Comment by bontus** [comment]
Can confirm this issue when using the pennbox dump file.

**Comment by nberkow** [comment]
I believe that table is deprecated. What is generating the error?

----- Original Message -----

**Comment by bontus** [comment]
Dear Nathan,
I don't quite understand your question, the error occurs when I try to load the provided dump file via "mysql -u root -p < structure_surfer.mysql" on a freshly installed system.
Best

**Comment by filipsPL** [comment]
The same problem here. Any solution?

**Comment by filipsPL** [comment]
A workaround could be to use `-f` (force) option, e.g., `mysql -u structure_surfer -p -f < structure_surfer.mysql`

**Comment by ate50eggs** [comment]
I found a line referring to the bad table. It must have been left there by a bad cat or something. I removed it with this:

sed 's/\/\*!40000 ALTER TABLE `gene_info` ENABLE KEYS \*\/;//' structure_surfer.mysql > structure_surfer.fixed.mysql

**Comment by ate50eggs** [comment]
The updated file is now available from PennBox

**Comment by filipsPL** [comment]
Thanks. Is a content of the updated file is different from the previous version (in terms of the science), or it is just a technical fix?

**Comment by nberkow** [comment]
Just a technical fix. No need to download the file again if you found your own workaround.
